dist: precise

language: php

php:
  - '7.2'

addons:
  mariadb: 10.4

cache:
  directories:
    - node_modules
    - vendor
  
before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan migrate
  
script:
  - vendor/bin/phpunit